site_name: Fab Lab Ísland 
site_description: Ár hvert hittist starfsfólk úr Fab Lab Íslands víðsvegar um allt land til að deila þekkingu og reynslu. 2025 verður haldið í Húsavík.
# site_url: 

theme:
  name: material
  logo: https://www.fla.is/img/faviconwhite.png
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

# Uncomment if using custom styles
# extra_css:
#   - stylesheets/extra.css

plugins:
  - search
  - git-authors:
      fallback_to_git: true
  - git-revision-date-localized:
      enable_creation_date: true
  - blog:
      blog_dir: Fabvarpið
      blog_toc: true
      post_url_format: "{slug}"
  - mkdocs-video:
      is_video: true
      video_controls: true
  - table-reader
  - caption

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - footnotes
  - attr_list
  - md_in_html
